-- Table: public.followings

-- DROP TABLE IF EXISTS public.followings;

CREATE TABLE followings
(
    id integer PRIMARY KEY generated by default as identity,
    offerid integer REFERENCES offers (id),
    userid integer REFERENCES users (id),
    timefollowed timestamptz NOT NULL
);