-- Table: public.offers

-- DROP TABLE IF EXISTS public.offers;

CREATE TABLE offers
(
    id integer PRIMARY KEY generated by default as identity,
    title character varying(200) NOT NULL,
    categoryid integer references categories(id),
    subcategoryid integer references subcategories(id),
    price numeric(12,4),
    currency char(1),
    userid integer references users(id),
    timeposted timestamp with time zone NOT NULL,
    closed boolean,
    timeclosed timestamp with time zone,
    postcode text,
    city text,
    address text,
    CONSTRAINT chk_price CHECK (price > 0)
);