-- Table: public.subcategories

-- DROP TABLE IF EXISTS public.subcategories;

CREATE TABLE subcategories
(
    id integer PRIMARY KEY generated by default as identity,
    categoryid int references categories(id),
    name character varying(50)
)